[package]
name = "glimpse"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
arboard = "3.4.1"
clap = { version = "4.5.23", features = ["derive"] }
colored = "2.2.0"
globset = "0.4.15"
ignore = "0.4.23"
indicatif = "0.17.9"
once_cell = "1.20.2"
rayon = "1.10.0"
walkdir = "2.5.0"
