[package]
name = "glimpse"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.23", features = ["derive"] }
colored = "2.2.0"
globset = "0.4.15"
indicatif = "0.17.9"
rayon = "1.10.0"
tree-sitter = "0.24.6"
walkdir = "2.5.0"
